const chatObjects = [
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Hello, how are you?",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Good morning!",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "I'll call you later.",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "What time is the meeting?",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Thanks for your help!",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "See you soon.",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Take care!",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Let's meet tomorrow.",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Can you send me the document?",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Have a great day!",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "I'll be there soon.",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Don't forget the meeting.",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Good luck with your project!",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Can you review my work?",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Let me know if you need help.",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "I appreciate your support.",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Let's catch up later.",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "I'll check on that for you.",
  },
  {
    sender_id: "1",
    receiver_id: "2",
    sender_name: "Alice",
    receiver_name: "Bob",
    message: "Have you completed the task?",
  },
  {
    sender_id: "2",
    receiver_id: "1",
    sender_name: "Bob",
    receiver_name: "Alice",
    message: "Yes, I just finished it!",
  },
];

export default chatObjects;
