const DummyMentors = [
  {
    id: 1,
    name: "John Doe",
    role: "mentor",
    email: "john.doe@example.com",
    expertise: "Software Development",
    yearsOfExperience: 5,
    location: "New York, USA",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "mentor",
    email: "jane.smith@example.com",
    expertise: "Data Science",
    yearsOfExperience: 8,
    location: "London, UK",
  },
  {
    id: 3,
    name: "Albert Green",
    role: "mentor",
    email: "albert.green@example.com",
    expertise: "Project Management",
    yearsOfExperience: 10,
    location: "Berlin, Germany",
  },
  {
    id: 4,
    name: "Emily Davis",
    role: "mentor",
    email: "emily.davis@example.com",
    expertise: "UI/UX Design",
    yearsOfExperience: 7,
    location: "Toronto, Canada",
  },
  {
    id: 5,
    name: "Michael Brown",
    role: "mentor",
    email: "michael.brown@example.com",
    expertise: "Machine Learning",
    yearsOfExperience: 6,
    location: "Sydney, Australia",
  },
  {
    id: 6,
    name: "Sophia Johnson",
    role: "mentor",
    email: "sophia.johnson@example.com",
    expertise: "Digital Marketing",
    yearsOfExperience: 4,
    location: "Los Angeles, USA",
  },
  {
    id: 7,
    name: "David Wilson",
    role: "mentor",
    email: "david.wilson@example.com",
    expertise: "Entrepreneurship",
    yearsOfExperience: 12,
    location: "San Francisco, USA",
  },
  {
    id: 8,
    name: "Olivia Taylor",
    role: "mentor",
    email: "olivia.taylor@example.com",
    expertise: "Cloud Computing",
    yearsOfExperience: 9,
    location: "Amsterdam, Netherlands",
  },
  {
    id: 9,
    name: "Lucas Martinez",
    role: "mentor",
    email: "lucas.martinez@example.com",
    expertise: "Business Strategy",
    yearsOfExperience: 15,
    location: "Madrid, Spain",
  },
  {
    id: 10,
    name: "Mia Anderson",
    role: "mentor",
    email: "mia.anderson@example.com",
    expertise: "Cybersecurity",
    yearsOfExperience: 11,
    location: "Paris, France",
  },
];

export default DummyMentors;
