const MentorsDummy = [
  {
    id: 1,
    name: "Arjun Sharma",
    age: 35,
    email: "arjun.sharma@example.com",
    specialization: "Mathematics",
    experience: 10,
  },
  {
    id: 2,
    name: "Priya Verma",
    age: 29,
    email: "priya.verma@example.com",
    specialization: "Physics",
    experience: 7,
  },
  {
    id: 3,
    name: "Rajesh Gupta",
    age: 42,
    email: "rajesh.gupta@example.com",
    specialization: "Chemistry",
    experience: 15,
  },
  {
    id: 4,
    name: "Anjali Nair",
    age: 30,
    email: "anjali.nair@example.com",
    specialization: "Computer Science",
    experience: 8,
  },
  {
    id: 5,
    name: "Vikram Singh",
    age: 38,
    email: "vikram.singh@example.com",
    specialization: "Biology",
    experience: 12,
  },
  {
    id: 6,
    name: "Sneha Patil",
    age: 27,
    email: "sneha.patil@example.com",
    specialization: "History",
    experience: 5,
  },
  {
    id: 7,
    name: "Kiran Reddy",
    age: 33,
    email: "kiran.reddy@example.com",
    specialization: "Economics",
    experience: 9,
  },
  {
    id: 8,
    name: "Meera Iyer",
    age: 41,
    email: "meera.iyer@example.com",
    specialization: "English Literature",
    experience: 14,
  },
  {
    id: 9,
    name: "Amit Mishra",
    age: 36,
    email: "amit.mishra@example.com",
    specialization: "Political Science",
    experience: 11,
  },
  {
    id: 10,
    name: "Nisha Kapoor",
    age: 28,
    email: "nisha.kapoor@example.com",
    specialization: "Psychology",
    experience: 6,
  },
  {
    id: 11,
    name: "Ravi Kumar",
    age: 39,
    email: "ravi.kumar@example.com",
    specialization: "Mechanical Engineering",
    experience: 13,
  },
  {
    id: 12,
    name: "Pooja Chauhan",
    age: 31,
    email: "pooja.chauhan@example.com",
    specialization: "Environmental Science",
    experience: 8,
  },
  {
    id: 13,
    name: "Sanjay Desai",
    age: 44,
    email: "sanjay.desai@example.com",
    specialization: "Physics",
    experience: 17,
  },
  {
    id: 14,
    name: "Kavita Joshi",
    age: 34,
    email: "kavita.joshi@example.com",
    specialization: "Mathematics",
    experience: 10,
  },
  {
    id: 15,
    name: "Akash Mehta",
    age: 40,
    email: "akash.mehta@example.com",
    specialization: "Computer Science",
    experience: 12,
  },
  {
    id: 16,
    name: "Leela Krishnan",
    age: 37,
    email: "leela.krishnan@example.com",
    specialization: "Philosophy",
    experience: 11,
  },
  {
    id: 17,
    name: "Vivek Bhatia",
    age: 45,
    email: "vivek.bhatia@example.com",
    specialization: "Statistics",
    experience: 18,
  },
  {
    id: 18,
    name: "Deepika Malhotra",
    age: 26,
    email: "deepika.malhotra@example.com",
    specialization: "Sociology",
    experience: 4,
  },
  {
    id: 19,
    name: "Manoj Pandey",
    age: 50,
    email: "manoj.pandey@example.com",
    specialization: "Civil Engineering",
    experience: 22,
  },
  {
    id: 20,
    name: "Shreya Bhattacharya",
    age: 32,
    email: "shreya.bhattacharya@example.com",
    specialization: "Music",
    experience: 9,
  },
];

export default MentorsDummy;
