const students = [
  {
    id: 1,
    name: "John Doe",
    age: 20,
    grade: "A",
    email: "john.doe@example.com",
    major: "Computer Science",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 22,
    grade: "B",
    email: "jane.smith@example.com",
    major: "Mathematics",
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 19,
    grade: "A",
    email: "alice.johnson@example.com",
    major: "Physics",
  },
  {
    id: 4,
    name: "Bob Brown",
    age: 21,
    grade: "C",
    email: "bob.brown@example.com",
    major: "Engineering",
  },
  {
    id: 5,
    name: "Eve Davis",
    age: 23,
    grade: "B",
    email: "eve.davis@example.com",
    major: "Biology",
  },
  {
    id: 6,
    name: "Charlie Wilson",
    age: 24,
    grade: "A",
    email: "charlie.wilson@example.com",
    major: "Chemistry",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    age: 20,
    grade: "B",
    email: "sophia.martinez@example.com",
    major: "Economics",
  },
  {
    id: 8,
    name: "James Anderson",
    age: 22,
    grade: "A",
    email: "james.anderson@example.com",
    major: "Psychology",
  },
  {
    id: 9,
    name: "Mia Taylor",
    age: 19,
    grade: "C",
    email: "mia.taylor@example.com",
    major: "Sociology",
  },
  {
    id: 10,
    name: "David Lee",
    age: 25,
    grade: "B",
    email: "david.lee@example.com",
    major: "History",
  },
];
export default students;
