export const ChatMemberApiData = [
  {
    id: 0,
    name: "Mentor 1",
    image: "avtar/16.jpg",
    status: "Hey, How are you?",
    online: "success",
    lastSeenDate: "0",
    time: "7:30 PM",
    reply: "fa fa-reply font-danger",
    badge: true,
  },
  {
    id: 1,
    name: "Mentor 3",
    image: "avtar/3.jpg",
    status: "Hey, How are you?",
    online: "success",
    lastSeenDate: "0",
    time: "7:30 PM",
    reply: "fa fa-reply font-danger",
    badge: true,
  },
  {
    id: 2,
    name: "Mentor 3",
    image: "avtar/11.jpg",
    status: "Thanks for reply",
    lastSeenDate: "Last seen yesterday 20:07",
    online: "success",
    time: "7:30 PM",
    reply: "fa fa-reply font-danger",
  },
  {
    id: 3,
    name: "Student",
    image: "avtar/7.jpg",
    status: "Hey, What's up?",
    lastSeenDate: "Last seen today 15:24",
    online: "success",
    time: "1:10 PM",
    reply: "fa fa-reply font-success",
  },
  {
    id: 4,
    name: "Ronald Richards",
    image: "avtar/16.jpg",
    status: "I'm ready",
    lastSeenDate: "Last seen today 13:24",
    online: "success",
    time: "13:10 PM",
    reply: "fa fa-reply font-success",
  },
  {
    id: 5,
    name: "Darlene Robertson",
    image: "avtar/4.jpg",
    status: "Hey, How are you?",
    lastSeenDate: "1:30 PM",
    online: "success",
    time: "1:30 PM",
    reply: "fa fa-reply font-success",
  },
  {
    id: 6,
    name: "Darrell Steward",
    image: "blog/comment.jpg",
    status: "What's going on?",
    lastSeenDate: "Last seen today 12:10",
    online: "warning",
    time: "2:10 PM",
    reply: "fa fa-reply font-success",
  },
  {
    id: 7,
    name: "Theresa Webb",
    image: "blog/4.jpg",
    status: "What's up?",
    lastSeenDate: "Last seen today 22:24",
    online: "success",
    time: "1:50 AM",
    reply: "fa fa-reply font-danger",
  }
];
