import { ProductItemInterface } from "@/Types/EcommerceType";

export const ProductApiData:ProductItemInterface[] = [
  {
    id: 1,
    image: "01.jpg",
    name: "Woman T-shirt",
    note: "Women Full Sweatshirt",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    status: "none",
    price: 26.0,
    stock: "Out of stock",
    review: "(120 review)",
    category: "Woman T-shirt",
    rating: 5,
    colors: ["White", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
      {
        color: "black",
        images: "03.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
    ],
  },
  {
    id: 2,
    image: "02.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "360.00",
    status: "Sale",
    ribbonClassName: "ribbon ribbon-danger",
    price: 30.0,
    stock: "In stock",
    review: "(120 review)",
    rating: 4,
    category: "Dream Beauty Fashion",
    colors: ["green", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Levis", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "05.jpg",
      },
      {
        color: "gray",
        images: "06.jpg",
      },
      {
        color: "gray",
        images: "07.jpg",
      },
      {
        color: "gray",
        images: "08.jpg",
      },
    ],
  },
  {
    id: 3,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    price: 26.0,
    ribbonClassName: "ribbon ribbon-danger",
    status: "none",
    stock: "In stock",
    review: "(200 review)",
    rating: 5,
    category: "VOXATI",
    colors: ["White", "gray", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Spykar", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
      {
        color: "gray",
        images: "04.jpg",
      },
    ],
  },
  {
    id: 4,
    image: "04.jpg",
    name: "Cyclamen",
    note: "Stylish co-ord set 2 for women",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    status: "50%",
    ribbonClassName: "ribbon ribbon-success ribbon-right",
    price: 30.0,
    stock: "In stock",
    review: "(410 review)",
    rating: 4,
    category: "Cyclamen",
    colors: ["red", "gray", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Lee", "Levis", "Hudson"],
    variants: [
      {
        color: "White",
        images: "05.jpg",
      },
      {
        color: "gray",
        images: "06.jpg",
      },
      {
        color: "gray",
        images: "07.jpg",
      },
      {
        color: "gray",
        images: "08.jpg",
      },
    ],
  },
  {
    id: 5,
    image: "02.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "360.00",
    price: 30.0,
    stock: "In stock",
    ribbonClassName: "ribbon ribbon-success ribbon-right",
    status: "none",
    review: "(120 review)",
    rating: 5,
    category: "Dream Beauty Fashion",
    colors: ["green", "White", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Spykar", "Denien"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 6,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Symbol women's Solid Regular Fit Full Sleeve Formal Shirt, Cotton Regular Fit women's Casual Shirt.",
    discountPrice: "400.00",
    price: 25.0,
    status: "Hot",
    ribbonClassName: "ribbon ribbon-warning",
    stock: "Out of stock",
    review: "(200 review)",
    rating: 4,
    category: "VOXATI",
    colors: ["purple", "orange", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Lee", "Diesel", "Levis"],
    variants: [
      {
        color: "White",
        images: "03.jpg",
      },
      {
        color: "gray",
        images: "04.jpg",
      },
    ],
  },
  {
    id: 7,
    image: "01.jpg",
    name: "Woman T-shirt",
    note: "Solid men's Dress",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    price: 26.0,
    status: "50%",
    ribbonClassName: "ribbon ribbon-warning",
    stock: "In stock",
    review: "(300 review)",
    rating: 5,
    category: "Woman T-shirt",
    colors: ["orange", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Lee", "Diesel"],
    variants: [
      {
        color: "White",
        images: "05.jpg",
      },
      {
        color: "blue",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 8,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Glamcci Women's Cotton Blend Printed TreckSuit Dress, Rayon Women's Regular Top.",
    discountPrice: "400.00",
    price: 26.0,
    status: "none",
    stock: "In stock",
    review: "(120 review)",
    rating: 4,
    category: "VOXATI",
    colors: ["purple", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "07.jpg",
      },
      {
        color: "gray",
        images: "08.jpg",
      },
      {
        color: "gray",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 9,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "400.00",
    price: 25.0,
    status: "none",
    stock: "Out of stock",
    review: "(200 review)",
    rating: 5,
    category: "VOXATI",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Spykar"],
    variants: [
      {
        color: "purple",
        images: "03.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "05.jpg",
      },
      {
        color: "White",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 10,
    image: "04.jpg",
    name: "Cyclamen",
    note: "Stylish co-ord set dress for women",
    description: "Symbol Men's Solid Regular Fit Full Sleeve Formal Shirt, Cotton Regular Fit Men's Casual Shirt.",
    discountPrice: "350.00",
    price: 30.0,
    status: "none",
    stock: "Out of stock",
    review: "(410 review)",
    rating: 4,
    category: "Cyclamen",
    colors: ["purple", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "07.jpg",
      },
      {
        color: "gray",
        images: "08.jpg",
      },
      {
        color: "gray",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 11,
    image: "02.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "360.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(120 review)",
    rating: 5,
    category: "Dream Beauty Fashion",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "03.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "05.jpg",
      },
      {
        color: "gray",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 12,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement..",
    discountPrice: "400.00",
    price: 26.0,
    status: "none",
    stock: "In stock",
    review: "(200 review)",
    rating: 4,
    category: "VOXATI",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "07.jpg",
      },
      {
        color: "pink",
        images: "08.jpg",
      },
      {
        color: "blue",
        images: "01.jpg",
      },
      {
        color: "purple",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 13,
    image: "02.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "360.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(300 review)",
    rating: 5,
    category: "Dream Beauty Fashion",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "03.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "05.jpg",
      },
      {
        color: "black",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 14,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "400.00",
    price: 25.0,
    status: "50%",
    ribbonClassName: "ribbon  ribbon-success",
    stock: "In stock",
    review: "(120 review)",
    rating: 4,
    category: "VOXATI",
    colors: ["White", "blue", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Lee"],
    variants: [
      {
        color: "White",
        images: "07.jpg",
      },
      {
        color: "blue",
        images: "08.jpg",
      },
      {
        color: "yellow",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 15,
    image: "04.jpg",
    name: "Cyclamen",
    note: "Stylish co-ord set dress for women",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    price: 30.0,
    status: "Hot",
    ribbonClassName: "ribbon ribbon-right ribbon-warning",
    stock: "In stock",
    review: "(200 review)",
    rating: 5,
    category: "Cyclamen",
    colors: ["black", "blue", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Lee"],
    variants: [
      {
        color: "black",
        images: "03.jpg",
      },
      {
        color: "blue",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "05.jpg",
      },
      {
        color: "yellow",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 16,
    image: "02.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Mylo Essentials Pre & Post Maternity/Nursing Maxi jeans with Both Sides Zipper..",
    discountPrice: "360.00",
    price: 30.0,
    status: "none",
    stock: "Out of stock",
    review: "(300 review)",
    rating: 4,
    category: "Dream Beauty Fashion",
    colors: ["black", "pink", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Hudson"],
    variants: [
      {
        color: "black",
        images: "07.jpg",
      },
      {
        color: "pink",
        images: "08.jpg",
      },
      {
        color: "yellow",
        images: "01.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 17,
    image: "03.jpg",
    name: "VOXATI",
    note: "Men's Denim Jacket",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    price: 26.0,
    status: "none",
    stock: "In stock",
    review: "(120 review)",
    rating: 5,
    category: "VOXATI",
    colors: ["White", "blue", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Lee"],
    variants: [
      {
        color: "White",
        images: "03.jpg",
      },
      {
        color: "blue",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "05.jpg",
      },
      {
        color: "pink",
        images: "06.jpg",
      },
    ],
  },
  {
    id: 18,
    image: "01.jpg",
    name: "Woman T-shirt",
    note: "Women Full Sweatshirt",
    description: "Elevate your casual wardrobe with our Women's T-Shirt, a versatile and comfortable addition to your everyday style.Crafted from soft and breathable cotton ease of movement.",
    discountPrice: "350.00",
    status: "none",
    price: 26.0,
    stock: "Out of stock",
    review: "(120 review)",
    category: "Woman T-shirt",
    rating: 4,
    colors: ["White", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "07.jpg",
      },
      {
        color: "gray",
        images: "08.jpg",
      },
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "02.jpg",
      },
    ],
  },
];
